modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "doaddonfluids"
version = "${version}"
displayName = "[Let's Do Addon] Fluids"
authors = "Ninjdai"
description = '''
Add fluids to the Let's Do series for even more modded usage !
'''
#logoFile = ""

[[dependencies.doaddonfluids]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doaddonfluids]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doaddonfluids]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddonfluids]]
modId = "meadow"
mandatory = false
versionRange = "[1.3.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddonfluids]]
modId = "vinery"
mandatory = false
versionRange = "[1.3.8,)"
ordering = "AFTER"
side = "BOTH"
