modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Ninjdai1/letsdo-addon-fluids/issues"
license = "GPLv3"

[[mods]]
modId = "doaddoncreate"
version = "${version}"
displayName = "[Let's Do Addon] Fluids"
authors = "Ninjdai"
description = '''
Add fluids to the Let's Do series for even more modded usage !
'''
logoFile = "assets/doaddoncreate/icon.png"

[[dependencies.doaddoncreate]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "botarium"
mandatory = true
versionRange = "[2.3.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.25,)"
ordering = "AFTER"
side = "BOTH"


[[dependencies.doaddoncreate]]
modId = "meadow"
mandatory = false
versionRange = "[1.3.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "vinery"
mandatory = false
versionRange = "[1.4.19,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.doaddoncreate]]
modId = "brewery"
mandatory = false
versionRange = "[1.1.8,)"
ordering = "AFTER"
side = "BOTH"
